export const messageLogs={
    EMAIL_REQUIRED:"Please Enter valid email.",
    VALID_MOBILE:"Please enter valid mobile number.",
    VALID_PASSWORD:"Please enter valid passoword, atleast 6 digits.",
    SIGNUP_SUCCESS:"User Created successfully..!",
    LOGIN_SUCCESS:"User logged in successfully..!",
    USER_EXIST:"User already exist in this platform.",
    USER_NOT_FOUND:"User not found in this platform",
    USER_UPDATE:"User deatils updated successfully",
    ERROR_MESSAGE:"Error has occured ,please contact tech team.",
    INVALID_API_KEY:"Please enter valid API key",
    NO_ACCESS:"Access Forbidden,No valid token",
    VALID_NAME:"Please enter valid name..!",
    USER_TOKEN:"Here is your user token.",
    SESSION_EXPIRED:"User session has been expired.",
    TOKEN_EXPIRES:"Token has expired",
    CHANGE_STATUS:"User status has changes successfully..!",
    VALID_USER_ID:"Please enter valid userId",
    VALID_COMPANY_NAME:"Please enter valid company name.",
    VALID_DEPT_ID:"DepartmentId is a required field.",
    VALID_CLIENT_ID:"ClientId is a required field.",
    VALID_CAMPAIGN_NAME:"Please enter valid campaign name",
    VALID_START_DATE:"Please enter valid start date",
    VALID_END_DATE:"Please enter valid end date",
    VALID_PAYOUT_CURRENCY_ID:"Please enter valid payout currency Id.",
    VALID_BUDGET:"Please enter valid budget amount",
    VALID_ORDER_ID:"Please enter valid order Id.",
    VALID_VOL:"Please enter valid volume amount.",
    VALID_PAYOUT:"PLease enter valid payout amount.",
    VALID_CAMP_TYPE:"PLease enter valid campaign type.",
    VALID_CAMP_DESC:"PLease enter valid campaign description.",
    ALL_CLIENTS:"Here is you all clients..!",
    CREATE_CLIENT:"Client created successfully",
    ALL_DEPTS:"Here is you all departments..!",
    ALL_CAMP_MODE:"Here is you all Campaign mode..!",
    CREATE_DEPT:"Department created successfully",
    DEPT_REQ:"Please enter valid department name.",
    CREATIVE_SIZE_REQ:"Please enter valid creative size.",
    CREATE_CREATIVE_SIZE:"Creative Size created successfully",
    CREATE_CREATIVE_TYPE:"Creative Type created successfully",
    ALL_CREATIVE_SIZES:"Here is you all creative sizes..!",
    ALL_CREATIVE_SIZES:"Here is you all creative type..!",
    CAMP_MODE_REQ:"Please enter valid campaign mode name.",
    CREATIVE_TYPE_REQ:"Please enter valid creative type name.",
    REQ_ACTIVE:"Please mention creative type status"
}
